import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "../globals.css";
import Navbar from "@/components/shared/Navbar";
import Image from "next/image";
import Banner from "@/components/shared/Banner";
import assets from "@/assets";
import { Button } from "@/components/ui/button";

const font = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={font.className}>
				<main className="w-100 flex flex-col overflow-x-hidden max-w-[100vw]">
					<Navbar />
					{children}
					
					<footer className="py-6 flex items-center justify-center bg-[#F2F5F6]">
						<p className="text-[16px] text-[#51595A] font-light">
							Copyright © 2023 – 2024 Al-Sadaq. All Rights Reserved.
						</p>
					</footer>
				</main>
			</body>
		</html>
	);
}
